# Main menu navigation
menu:
  é¦–é¡µ: / || fas fa-home
  æ ‡ç­¾: /tags/ || fas fa-tags
  åˆ†ç±»: /categories/ || fas fa-folder-open
  å…³äº: /about/ || fas fa-heart
  å…¶ä»–||fas fa-list:
    å½’æ¡£: /archives/ || fas fa-asterisk
    æ›´æ–°æ—¥å¿—: /update/ || fas fa-archive

# Avatar
avatar:
  img: /img/avatar.jpg
  effect: false

# Nav related settings
nav:
  logo: # image url
  display_title: true
  fixed: true

# Main page settings
index_img: /img/background.png
default_top_img: /img/background.png
index_top_img_height: 100vh
footer_img: false

# Site subtitle settings
subtitle:
  enable: true
  # Typewriter Effect
  effect: true
  # Customize typed.js (https://github.com/mattboldt/typed.js/)
  typed_option:
    strings: ['ä¸æ•¢ç›¸ä¿¡ï½', 'ç°¡ç›´å…«é»æª”ï¼']
    startDelay: 300
    typeSpeed: 150
    loop: true
    loopCount: Infinity
    backSpeed: 50
    showCursor: true
    cursorChar: '|'

# Cover image settings
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover:
    - /img/background.png

# Search
local_search:
  enable: true
  preload: true
  top_n_per_article: 1
  unescape: true
  CDN:

# Code highlighting theme
highlight_theme: light
highlight_copy: true
highlight_lang: true
highlight_shrink: false
code_word_wrap: false

# Copy text settings
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50

# Social media links
social:
  fab fa-github: https://github.com/maomao725 || Github
  fas fa-envelope: mailto:yejiale25@gmail || Email

# Share
share:
  enable: false

# Comment system
comments:
  use: Utterances
  text: true
  lazyload: false
  count: false
  card_post_count: false

# Utterances
# https://utteranc.es/
utterances:
  repo: maomao725/maomao725.github.io
  # Issue Mapping: pathname/url/title/og:title
  issue_term: pathname
  # Theme: github-light/github-dark/github-dark-orange/icy-dark/dark-blue/photon-dark
  light_theme: github-light
  dark_theme: photon-dark

# Online Chat
chat:
  enable: false

# Footer settings
footer:
  owner:
    enable: true
    since: 2025
  custom_text: '<div id="runtime"></div><div style="margin-top: 5px;">Copyright Â© 2025 æ¯›æ¯›</div>'
  copyright: true

# Aside widget settings
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: è‡ªèƒ½ç”Ÿç¾½ç¿¼ï¼Œä½•å¿…ä»°äº‘æ¢¯
    button:
      enable: true
      icon: fab fa-github
      text: å…³æ³¨æˆ‘
      link: https://github.com/maomao725
  card_announcement:
    enable: true
    content: ğŸš€ é‡å¯çºªå…ƒï¼Œè®°å½•æŠ€æœ¯æˆé•¿çš„ç‚¹ç‚¹æ»´æ»´
  card_recent_post:
    enable: true
    limit: 5
    sort: date
    sort_order: desc
  card_categories:
    enable: true
    limit: 8
    expand: none
    sort_order:
  card_tags:
    enable: true
    limit: 40
    color: false
    sort_order:
  card_archives:
    enable: true
    type: monthly
    format: MMMM YYYY
    order: desc
    limit: 8
    sort_order:
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order:
      - post_count
      - last_push_date

# Post settings
post:
  meta:
    author:
      enable: false
    date:
      enable: true
      format: 'YYYY-MM-DD'
    updated:
      enable: true
      date_format: 'YYYY-MM-DD'
    categories:
      enable: true
    tags:
      enable: true
  award:
    enable: false
  copyright:
    enable: true
    decode: false
    author_href:
    license: CC BY-NC-SA 4.0
    license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Related Articles
related_post:
  enable: true
  limit: 6
  date_type: created

# Dark mode
darkmode:
  enable: true
  button: true
  autoChangeMode: false

# CDN settings
CDN:
  internal_provider: jsdelivr
  third_party_provider: jsdelivr
  option:

# Math (KaTeX)
math:
  enable: false
  per_page: false
  hide_scrollbar: false
  engine: mathjax
  mathjax:
    enableMenu: true
    tags: false

# Medium Zoom
medium_zoom: false

# Image lazy loading
lazyload:
  enable: false

# Sidebar related
toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false
  scroll_percent: true

# Reading progress
reading_progress:
  enable: false

# Auto scroll
auto_scroll: false

# Beautify/Effect
beautify:
  enable: false
  field: post
  title-prefix-icon:
  title-prefix-icon-color:

# Global font
font:
  global-font-size:
  code-font-size:
  font-family:
  code-font-family:

# Website analytic
baidu_analytics:
google_analytics:

# Performance
preloader:
  enable: false

# Word Count Settings
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# PWA
pwa:
  enable: false

# Inject
inject:
  head:
    - <link rel="stylesheet" href="/css/custom.css">
  bottom:
    - <script src="/js/nav-scroll.js"></script>
    - <script src="/js/runtime.js"></script>
    - <script src="/js/wordcount.js"></script>

# Disable copy
disable_copy: false
disable_selection: false

# Dev console
console: false